title: appliedml42
permalink: ':title/'
baseurl:
url:
site-twitter:

# Author Settings
author: appliedml42
author-img: logo.jpg
about-author: Resources for applying machine learning.
social-twitter: appliedml42
social-github: appliedml42
social-linkedin: abhishekpatnia
social-email: appliedml42@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
